---
- name: fail unless go_user is defined
  fail: msg="go_user must be set."
  when: go_user is not defined

- name: get go user details
  command: sh -c 'echo $HOME'
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  changed_when: false
  register: go_user_check
  vars:
    ansible_ssh_pipelining: "{{ is_macos }}"

- name: set go user home
  set_fact: go_user_home="{{ go_user_check.stdout_lines[0] }}"

- name: include system tasks
  include_tasks: system.yml

- name: include user tasks
  include_tasks: user.yml

# install additional dependencies
- name: install additional go system packages
  package: name={{ item }} state=present
  with_items: "{{ addtl_go_system_packages }}"

- name: install additional go user packages
  command: "go get -u {{ item }}"
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  with_items: "{{ addtl_go_user_packages }}"
