---
- name: fail unless go_user is defined
  fail: msg="go_user must be set."
  when: go_user is not defined

- name: discover os facts
  include: discover/os.yml

- name: discover go facts
  include: discover/go.yml

- name: include system tasks
  include: system.yml

- name: include user tasks
  include: user.yml

# install additional dependencies
- name: install additional go system packages
  package: name={{ item }} state=present
  with_items: "{{ addtl_go_system_packages }}"

- name: install additional go user packages
  command: "go get -u {{ item }}"
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  with_items: "{{ addtl_go_user_packages }}"
