---
- name: fail when user is not defined
  fail:
    msg: "go_user is not defined or is empty, it must be set."
  when: (go_user is not defined) or (not go_user)

- name: execute tasks
  include_tasks: "{{ include_task_item }}"
  loop:
    - include/00-facts.yml
    - include/10-apt-refresh.yml
    - include/20-packages.yml
    - include/30-install.yml
    - include/40-dep.yml
    - include/90-profile.yml
  loop_control:
    loop_var: include_task_item
