---
# tasks file for godev
 - name: create install dir
   file: path={{ go_install_dir }} state=directory
   become: true

 - name: download
   unarchive:
     src: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
     remote_src: true
     dest: "{{ go_install_dir }}"
     extra_opts: ["--strip-components=1"]
   become: true

 - name: create symlink
   file:
     state: link
     src: "{{ go_install_dir }}"
     dest: "{{ go_goroot_dir }}"
     mode: "0755"
     owner: root
     group: root
   become: true

 - name: configure environment
   template:
     src: go-profile.d.sh.j2
     dest: "{{ profile_d_path }}/go.sh"
     owner: root
     group: root
     mode: 0755
