---
# tasks file for godev
 - name: define user facts
   set_fact:
     install_dir: "{{ ansible_env.HOME }}/go{{ version }}"
     become_user: "{{ ansible_user_id }}"
   when: not global

 - name: define global facts
   set_fact:
     install_dir: /usr/local/go{{ version }}
     become: true
   when: global

 - name: create install dir
   file: path={{ install_dir }} ensure=directory
   become: "{{ become }}"

 - name: download
   unarchive:
     src: https://storage.googleapis.com/golang/go{{ version }}.linux-amd64.tar.gz
     remote_src: true
     dest: "{{ install_dir }}"
     extra_opts: ["--strip-components=1"]
   become: "{{ become }}"
