---
- name: create install dir
  file: path={{ go_install_dir }} state=directory
  become: true

- name: update apt cache
  apt: update_cache=true cache_valid_time=3600
  become: true
  when: is_ubuntu_derivative

- name: install git
  package: name=git state=present
  become: true

- name: download
  unarchive:
    src: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
    remote_src: true
    dest: "{{ go_install_dir }}"
    extra_opts: ["--strip-components=1"]
    creates: "{{ go_install_dir }}/bin/go"
  become: true

- name: create symlink
  file:
    state: link
    src: "{{ go_install_dir }}"
    dest: "{{ go_goroot_dir }}"
    mode: "0755"
    owner: root
    group: root
  become: true

- name: configure environment
  template:
    src: go-profile.d.sh.j2
    dest: /etc/profile.d/go.sh
    owner: root
    group: root
    mode: 0755
  become: true
