---
- name: create install dir
  file: path={{ go_install_dir }} state=directory
  become: true

- name: update apt cache
  apt: update_cache=true cache_valid_time=3600
  become: true
  when: is_ubuntu_derivative

- name: fix homebrew ownership
  command: find /usr/local -mindepth 1 -maxdepth 1 -type d -exec chown -R {{ go_user }}:admin {} \;
  become: true
  when: is_macos

- name: install git
  package: name=git state=present
  become: true
  become_user: |-
    {%- if is_linux -%}
      root
    {%- else -%}
      {{ go_user }}
    {%- endif -%}
  become_flags: -Hi
  vars:
    ansible_ssh_pipelining: "{{ is_macos }}"

- name: install GNU tar
  package: name=gnu-tar state=present
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  when: is_macos
  vars:
    ansible_ssh_pipelining: "{{ is_macos }}"

- name: download
  unarchive:
    src: https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz
    remote_src: true
    dest: "{{ go_install_dir }}"
    extra_opts: ["--strip-components=1"]
    creates: "{{ go_install_dir }}/bin/go"
  become: true

- name: create symlink
  file:
    state: link
    src: "{{ go_install_dir }}"
    dest: "{{ go_goroot_dir }}"
    mode: "0755"
    owner: root
    group: |-
      {%- if is_macos -%}
        admin
      {%- else -%}
        root
      {%- endif -%}
  become: true

- name: configure environment
  template:
    src: go-profile.d.sh.j2
    dest: /etc/profile.d/go.sh
    owner: root
    group: |-
      {%- if is_macos -%}
        admin
      {%- else -%}
        root
      {%- endif -%}
    mode: 0755
  become: true
