---
- name: create user go path
  file:
    path: "{{ go_user_path.replace('$HOME', go_user_home) }}/bin"
    state: directory
    mode: 0700
    owner: "{{ go_user }}"
    group: |-
      {%- if is_macos -%}
        primarygroup
      {%- else -%}
        {{ go_user }}
      {%- endif -%}
    recurse: true

- name: detect dep current version
  shell: "dep version | head -2 | tail -1 | awk -F ' : ' '{print $2;}' | cut -b 2-"
  environment:
    GOPATH: "{{ go_user_path.replace('$HOME', go_user_home) }}"
    GOROOT: "{{ go_goroot_dir }}"
  become: true
  become_user: "{{ go_user }}"
  changed_when: false
  failed_when: false
  register: godep_version_result

- name: detect dep latest version
  uri:
    url: "{{ godep_github_repo_url }}/releases/latest"
    status_code: 302
    follow_redirects: false
  register: godep_latest_result
  changed_when: false
  when: godep_version == "latest"

- name: set godep current version
  set_fact:
    godep_current_version: "{{ godep_version_result.stdout }}"
- name: set godep latest version
  set_fact:
    godep_latest_version: "{{ godep_latest_result.location | regex_replace(godep_github_version_regex | trim, godep_github_version_replace | trim) }}"
  when: godep_version == 'latest'

- name: set godep target version
  set_fact:
    godep_target_version: "{% if godep_version == 'latest' %}{{ godep_latest_version }}{% else %}{{ godep_version }}{% endif %}"

- name: dump debugging information
  debug:
    msg: |
      current: {{ godep_current_version | default('undefined') }}; \
      latest: {{ godep_latest_version | default('undefined') }}; \
      target: {{ godep_target_version | default('undefined') }}
  when: godep_debug | default(false)

- name: install dep
  get_url:
    url: https://github.com/golang/dep/releases/download/v{{ godep_target_version }}/dep-linux-amd64
    dest: "{{ go_user_path.replace('$HOME', go_user_home) }}/bin/dep"
    owner: "{{ go_user }}"
    group: |-
      {%- if is_macos -%}
        primarygroup
      {%- else -%}
        {{ go_user }}
      {%- endif -%}
    mode: 0755
    force: true
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  when: godep_current_version != godep_target_version
