---
- name: create go installation root
  file:
    path: "{{ go_user_install_dir }}"
    state: directory
    owner: "{{ go_user }}"
    group: "{{ go_user }}"
    recurse: true
  become: true
  become_user: "{{ go_user }}"

- name: create go path
  file:
    path: "{{ go_user_path.replace('$HOME', go_user_home) }}/bin"
    state: directory
    owner: "{{ go_user }}"
    group: "{{ go_user }}"
    recurse: true
  become: true
  become_user: "{{ go_user }}"

- name: download
  unarchive:
    src: "https://storage.googleapis.com/golang/go{{ go_version }}.linux-amd64.tar.gz"
    dest: "{{ go_user_install_dir }}"
    remote_src: true
    extra_opts: ["--strip-components=1"]
    creates: "{{ go_user_install_dir }}/bin/go"
  become: true
  become_user: "{{ go_user }}"

- name: link
  file:
    src: "{{ go_user_install_dir }}"
    dest: "{{ go_goroot_dir }}"
    state: link
    owner: "{{ go_user }}"
    group: "{{ go_user}}"
  become: true
  become_user: "{{ go_user }}"
