---
- name: get go user details
  command: sh -c 'echo $HOME'
  become: true
  become_user: "{{ go_user }}"
  become_flags: -Hi
  changed_when: false
  register: go_user_check

- name: set go user home
  set_fact: go_user_home="{{ go_user_check.stdout_lines[0] }}"
